### PR TITLE
No need to register the plugin

### PR DESCRIPTION
**Pull request by pconesa**
Bibtex should be just the docstring of the module

### CODE REVIEW

**Review by rmarabini — APPROVED** [review]
I guess thias is OK

**Comment by pconesa** [comment]
HI, this is not released yes and users are getting the warning:
WARNING FOR DEVELOPERS:  ccp4/bibtex._bibtex unnecessarily declared. Just the doc string is enough.
WARNING FOR DEVELOPERS:  ccp4/bibtex._bibtex unnecessarily declared. Just the doc string is enough.

Is it possible to just release this fix, if you are not planning for a release anytime soon?

**Comment by rmarabini** [comment]
Do you mean merging master with devel?


    Roberto

**Comment by pconesa** [comment]
no, sending this changes to master + a version bump to automatically release them.
https://github.com/scipion-em/scipion-em-ccp4/blob/master/ccp4/__init__.py#L167
https://github.com/scipion-em/scipion-em-ccp4/blob/master/ccp4/bibtex.py#L71

**Comment by pconesa** [comment]
I've made a PR #15  to remove the warnings and release. Hotfix on master. Nothing taken from devel except the warning fix.

**Pull request merged**
